item {
  id: 1
  name: 'Diego Velazquez'
}

item {
  id: 2
  name: 'Maria Agustina'
}

item {
  id: 3
  name: 'Infanta Margarita'
}

item {
  id: 4
  name: 'Isabel de Velasco'
}

item {
  id: 5
  name: 'Mari Barbola'
}

item {
  id: 6
  name: 'Platon'
}

item {
  id: 7
  name: 'Aristoteles'
}

item {
  id: 8
  name: 'Heraclito'
}

item {
  id: 9
  name: 'Gioconda'
}

item {
  id: 10
  name: 'Jesucristo'
}

item {
  id: 11
  name: 'Judas'
}

item {
  id: 12
  name: 'Mateo'
}